/****** Script for SelectTopNRows command from SSMS  ******/
SELECT * FROM [CodeAcademy].[dbo].[DARBUOTOJAS]
select [ASMENSKODAS], [VARDAS], [PAVARDE], [GIMIMOMETAI] 
FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [GIMIMOMETAI] < '1988';
select * FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [GIMIMOMETAI] < '1988-07-29';
select [DIRBANUO], [GIMIMOMETAI] FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [DIRBANUO] BETWEEN '2009-10-30' AND '2012-11-11';
select [VARDAS], [SKYRIUS_PAVADINIMAS], [PROJEKTAS_ID] FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [PROJEKTAS_ID] in (2,3);
select [VARDAS], [PAVARDE], [ASMENSKODAS] FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [ASMENSKODAS] LIKE '4%';
select * FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [GIMIMOMETAI] LIKE '12';
SELECT * FROM [CodeAcademy].[dbo].[PROJEKTAS] WHERE [PAVADINIMAS] LIKE '%u%'
select * FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [PAREIGOS] IS NULL;
SELECT [VARDAS], [PAVARDE], [DIRBANUO], [PAREIGOS] FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [DIRBANUO] > '2011-02-12' AND [PAREIGOS] = 'Programuotojas';
SELECT [VARDAS], [PAVARDE], [SKYRIUS_PAVADINIMAS], [PROJEKTAS_ID] FROM [CodeAcademy].[dbo].[DARBUOTOJAS] WHERE [SKYRIUS_PAVADINIMAS] = 'Java' OR [PROJEKTAS_ID] = '1';
SELECT VARDAS FROM DARBUOTOJAS except select VARDAS FROM DARBUOTOJAS WHERE VARDAS like 'S%';
SELECT VARDAS, DIRBANUO, GIMIMOMETAI FROM DARBUOTOJAS except select VARDAS,DIRBANUO,GIMIMOMETAI FROM DARBUOTOJAS WHERE DIRBANUO between '2009-10-30' and '2012-11-11';
select VARDAS, PAVARDE, GIMIMOMETAI FROM DARBUOTOJAS ORDER BY GIMIMOMETAI;
select VARDAS, PAVARDE, GIMIMOMETAI FROM DARBUOTOJAS ORDER BY GIMIMOMETAI desc;
select MAX(PROJEKTAS_ID) as MAX , MIN (PROJEKTAS_ID) as MIN from DARBUOTOJAS; 
select PROJEKTAS_ID, COUNT(*)AS Persons FROM DARBUOTOJAS GROUP BY PROJEKTAS_ID HAVING [PROJEKTAS_ID] is not Null
